import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import NavMenu from "./components/Navbar";
import Footer from "./components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className="dark:bg-slate-800">
        <Providers>
          <header >
            <NavMenu />
          </header>

          <main className="w-full" >{children}</main>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
